module.exports = {
  searchKeywords: [
    // Medical Director / Leadership
    'Veterinarian Medical Director',
    'DVM Medical Director',
    'Veterinary Clinical Director',
    'Veterinary Chief of Staff',
    'Chief of Staff DVM',
    'Veterinary Practice Owner',
    'Veterinary Hospital Director',
    // Equine / Large Animal
    'Equine Veterinarian',
    'Equine Medical Director',
    'Large Animal Veterinarian',
    'Large Animal Medical Director',
    'Equine Practitioner',
    'Horse Veterinarian',
    // Relief / Locum
    'Relief Veterinarian',
    'Locum Veterinarian',
    'Locum Tenens Veterinarian',
    'Per Diem Veterinarian',
    'Relief DVM',
    // General experienced DVMs
    'Associate Veterinarian',
    'Staff Veterinarian'
  ],
  locations: [
    'United States',
    // High-volume US states
    'California', 'Texas', 'New York', 'Florida', 'Illinois',
    'Ohio', 'Pennsylvania', 'Georgia', 'North Carolina', 'Michigan',
    'Virginia', 'Washington', 'Arizona', 'Colorado', 'Tennessee',
    'Massachusetts', 'Connecticut', 'Maryland', 'New Jersey', 'Oregon',
    'Nevada', 'Minnesota', 'Wisconsin', 'Indiana', 'Missouri',
    'Oklahoma', 'South Carolina', 'Kentucky', 'Louisiana', 'Iowa',
    // Canada
    'Canada', 'Ontario', 'British Columbia', 'Alberta', 'Manitoba',
    'Saskatchewan', 'Quebec', 'Nova Scotia'
  ],
  jobBoards: [
    'linkedin.com',
    'indeed.com',
    'vetmedJobs.com',
    'vetcareers.net',
    'reliefvets.com',
    'vettedpetcare.com',
    'nexgenvets.com',
    'dvm360.com/jobs'
  ],
  vetNetworks: [
    // ── National (US) ────────────────────────────────────────────────────────
    'AVMA (American Veterinary Medical Association)',
    'AAHA (American Animal Hospital Association)',
    'AAEP (American Association of Equine Practitioners)',
    'AAVMC (Association of American Veterinary Medical Colleges)',
    'NAVC (North American Veterinary Community)',
    // ── National (Canada) ────────────────────────────────────────────────────
    'CVMA (Canadian Veterinary Medical Association)',
    // ── US State VMAs ────────────────────────────────────────────────────────
    'AVMA-AL (Alabama Veterinary Medical Association)',
    'AKVMA (Alaska Veterinary Medical Association)',
    'AVMA-AZ / AzVMA (Arizona Veterinary Medical Association)',
    'AVMA-AR (Arkansas Veterinary Medical Association)',
    'CVMA (California Veterinary Medical Association)',
    'ColoVMA (Colorado Veterinary Medical Association)',
    'CVMA-CT (Connecticut Veterinary Medical Association)',
    'DVMA (Delaware Veterinary Medical Association)',
    'FVMA (Florida Veterinary Medical Association)',
    'GVMA (Georgia Veterinary Medical Association)',
    'HVMA (Hawaii Veterinary Medical Association)',
    'IVMA (Idaho Veterinary Medical Association)',
    'ISVMA (Illinois State Veterinary Medical Association)',
    'InVMA (Indiana Veterinary Medical Association)',
    'IVMA-IA (Iowa Veterinary Medical Association)',
    'KVMA (Kansas Veterinary Medical Association)',
    'KVMA-KY (Kentucky Veterinary Medical Association)',
    'LVMA (Louisiana Veterinary Medical Association)',
    'MVMA-ME (Maine Veterinary Medical Association)',
    'MVMA-MD (Maryland Veterinary Medical Association)',
    'MVMA (Massachusetts Veterinary Medical Association)',
    'MVMA-MI (Michigan Veterinary Medical Association)',
    'MVMA-MN (Minnesota Veterinary Medical Association)',
    'MVMA-MS (Mississippi Veterinary Medical Association)',
    'MVMA-MO (Missouri Veterinary Medical Association)',
    'MVMA-MT (Montana Veterinary Medical Association)',
    'NVMA-NE (Nebraska Veterinary Medical Association)',
    'NVMA (Nevada Veterinary Medical Association)',
    'NHVMA (New Hampshire Veterinary Medical Association)',
    'NJVMA (New Jersey Veterinary Medical Association)',
    'NMVMA (New Mexico Veterinary Medical Association)',
    'NYSVMS (New York State Veterinary Medical Society)',
    'NCVMA (North Carolina Veterinary Medical Association)',
    'NDVMA (North Dakota Veterinary Medical Association)',
    'OVMA (Ohio Veterinary Medical Association)',
    'OVMA-OK (Oklahoma Veterinary Medical Association)',
    'OVMA-OR (Oregon Veterinary Medical Association)',
    'PVMA (Pennsylvania Veterinary Medical Association)',
    'RIVMA (Rhode Island Veterinary Medical Association)',
    'SCVMA (South Carolina Veterinary Medical Association)',
    'SDVMA (South Dakota Veterinary Medical Association)',
    'TVMA-TN (Tennessee Veterinary Medical Association)',
    'TVMA (Texas Veterinary Medical Association)',
    'UVMA (Utah Veterinary Medical Association)',
    'VVMA (Vermont Veterinary Medical Association)',
    'VVMA-VA (Virginia Veterinary Medical Association)',
    'WSVMA (Washington State Veterinary Medical Association)',
    'WVVMA (West Virginia Veterinary Medical Association)',
    'WVMA (Wisconsin Veterinary Medical Association)',
    'WYVMA (Wyoming Veterinary Medical Association)',
    // ── Canadian Provincial Associations / Regulatory Colleges ───────────────
    'ABVMA (Alberta Veterinary Medical Association)',
    'CVBC (College of Veterinarians of British Columbia)',
    'CVO (College of Veterinarians of Ontario)',
    'MVMA-MB (Manitoba Veterinary Medical Association)',
    'SVMA (Saskatchewan Veterinary Medical Association)',
    'NSVM (Nova Scotia Veterinary Medical Association)',
    'NBVMA (New Brunswick Veterinary Medical Association)',
    'OMVQ (Ordre des médecins vétérinaires du Québec)',
    // ── City-Level / Metro VMA Affiliates ────────────────────────────────────
    'Chicago Veterinary Medical Association',
    'New York City Veterinary Medical Society',
    'Los Angeles Veterinary Medical Association',
    'Dallas-Fort Worth Veterinary Medical Association',
    'Houston Veterinary Medical Association',
    'Atlanta Veterinary Medical Association',
    'San Francisco Veterinary Medical Association',
    'Seattle Veterinary Medical Association',
    'Denver Veterinary Medical Association',
    'Phoenix Veterinary Medical Association',
    'Miami Veterinary Medical Association',
    'Boston Veterinary Medical Association',
    'Philadelphia Veterinary Medical Association',
    'Washington DC Veterinary Medical Association',
    'Twin Cities Veterinary Medical Association',
    'Columbus Veterinary Medical Association',
    'Indianapolis Veterinary Medical Association',
    'Portland Veterinary Medical Association',
    'Toronto Veterinary Medical Association',
    'Vancouver Veterinary Medical Association'
  ],
  runInterval: 1440,
  outputFormat: 'csv',
  minExperience: 3,
  saveLocation: './candidates.csv'
};
